version: '3.3'
services:
  postgres:
    image: postgres:12
    container_name: receitas-pg2
    environment:
      POSTGRES_DB: receitasdb2
      POSTGRES_USER: receitasdb2
      POSTGRES_PASSWORD: receitas2
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
