# Generated by Django 4.0.5 on 2022-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publica',
            field=models.BooleanField(default=False),
        ),
    ]
